### ISSUE TITLE
Compiler errors when opening in Unity, Vosk.dll not referenced?

### ISSUE THREAD

**Issue by alexmejda** [Yeti47/Vosk4Unity#2] opened 2021-09-20 19:59 UTC
Hello, 

First of all, this is a really cool project and exactly what I was looking for for quite a while but unable to do myself, so thanks for doing the work! (I'm looking to use Vosk in a VR game prototype that runs both on Windows and Oculus Quest standalone)

I hope it's okay to open an issue here. I tried opening the project in the correct Unity version, however, I get 3 compiler errors because the types/namespaces 'Vosk', 'VoskRecognizer' and 'Model' can't be found. 

I assumed this was caused by the Vosk.dll not loading correctly / not being referenced in the assembly definition for some reason. The assembly definition has indeed a missing reference but I can't reference anything vosk related. I can't include them as assembly references with 'Override References' either. 

Also when I tried to enable 'Load on startup' on the vosk.dll and the other libraries in the project, they all throw an exception along the lines of: 

Failed to load 'Assets/lib/Vosk.dll', expected x64 architecture, but was Unknown architecture. You must recompile your plugin for x64 architecture.

Vosk is available in 64bit though right? And Unity has phased out 32bit for quite a while now, so I assume something is wrong here and the libraries should not really be 32bit?

Any help would be greatly appreciated! 

Cheers, Alex

**Comment by Yeti47** [comment] 2021-09-21 14:37
Hi Alex,
thanks for raising this issue. Please note that the project is still in development. It's only been tested on Unity 2019 on a windows machine. 

However, I just did some tests and it turns out, the external DLLs only work in 32bit mode, which is most likely the cause of this problem. I will look into that and give you an update asap.

Thanks again.

**Comment by Yeti47** [comment] 2021-09-21 15:16
Hi again, 
I opened the project in Unity 2021 and ran the example and it worked perfectly fine.

The assembly definition Yetibyte.Unity.SpeechRecognition does not use the 'Override References' flag, so Unity will automatically reference all external assemblies that have the 'Auto Reference' flag enabled (which is the case for Vosk.dll). So no need to manually set up the reference to Vosk.dll.

Can you tell me what OS you are running Unity on?

**Comment by Yeti47** [comment] 2021-09-21 16:31
Could you try it again? I upgraded the project to Unity v. 2021 and reimported the DLLs as 64-bit versions. It seems to work for me.

**Please note:** Now that the project only includes the 64-bit versions of the external DLLs, only Windows x64 is supported as a target build platform. If you want to deploy to Windows x86 machines, you need to replace the DLLs with their 32-bit versions. I will eventually create two releases, one for targeting 64-bit machines and one for targeting 32-bit machines.

**Update:**
You no longer need to download or clone the repo. I created a pre-release version which can be downloaded [here](https://github.com/Yeti47/Vosk4Unity/releases/tag/v0.1-x64-pre). Simply import the Unity package file into your Unity project.

**Comment by alexmejda** [comment] 2021-09-22 10:16
Hey, 
this is great, will download the package and test it asap. 
Probably not relevant anymore, but the issue happened with:  Windows 10 64 bit, Unity versions 2019.4.0f1, 2019.4.30, 2020.2.3f1.
Will update you on progress with the package version. Thanks for the quick replies!

**Comment by alexmejda** [comment] 2021-09-22 11:21
Me again, I tested the package on Windows 10 in 2021.1.20f1 and the example scene works, so that's great! 

FYI, in 2020.2.3f1, there's still a compiler error:

Assets\Src\Yetibyte.Unity.SpeechRecognition\ModelManagement\HttpVoskModelInfo.cs(71,21): error CS1069: The type name 'ZipFile' could not be found in the namespace 'System.IO.Compression'. This type has been forwarded to assembly 'System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' Consider adding a reference to that assembly.

I will probably migrate my project to 2021, but it might be worth fixing for support of 2020 versions.

Also it might be noteworthy that on my system the Yetibyte.Unity.SpeechRecognition assembly definition (in Unity 2021 as well as 2020) has a missing assembly definition reference. Might just be a leftover from a previous version and will be ignored anyway, but maybe it is missing a reference? 

![missing_reference](https://user-images.githubusercontent.com/50108887/134334812-5231230e-af49-492d-ae80-47f16805e3b4.PNG)

Thanks for the quick help! I'm happy to do more testing if needed.

Cheers Alex

**Comment by Yeti47** [comment] 2021-09-22 11:49
Hi, thanks for your feedback.

I just tested it in Unity 2020 and it worked fine for me. The reason it did not work for you was because you probably had the API compatibility set to ".NET 4.x":

![image](https://user-images.githubusercontent.com/15141246/134338111-6d9ec190-5063-4171-b883-10a55da1f785.png)

Prior to .NET Standard 2.0, the ZipFile class was included in a separate assembly, as you aleady stated. I may implement some conditional compiling using pre-processor directives in order to support both .NET versions, but generally it should work with .NET Standard 2.0+.

**Comment by alexmejda** [comment] 2021-09-22 12:26
I just looked it up and yes, the 2020 project was on .NET 4.x, turns out creating a project from the URP template sets it to 4.x (while simply importing URP does not). Thanks again!

**Comment by Yeti47** [comment] 2021-09-22 15:20
I implemented conditional compiling to support both .NET Standard and .NET Framework 4.x. Thanks for the hint. I'll close this issue now. Hope you have a great day! :)

**Closed as completed by Yeti47** 2021-09-22 15:20 UTC
